var searchData=
[
  ['r_5fdebug',['r_debug',['../d5/d81/structr__debug.html',1,'']]],
  ['radio_5fsession_5ft',['radio_session_t',['../df/d7a/classzmq_1_1radio__session__t.html',1,'zmq']]],
  ['radio_5ft',['radio_t',['../d2/d1a/classzmq_1_1radio__t.html',1,'zmq']]],
  ['range1d',['Range1D',['../d9/d8e/class_teuchos_1_1_range1_d.html',1,'Teuchos']]],
  ['rangeerror',['RangeError',['../d8/d1b/class_teuchos_1_1_range_error.html',1,'Teuchos']]],
  ['rangevalidatordependency',['RangeValidatorDependency',['../d9/dd2/class_teuchos_1_1_range_validator_dependency.html',1,'Teuchos']]],
  ['rangevalidatordependencyxmlconverter',['RangeValidatorDependencyXMLConverter',['../d3/d22/class_teuchos_1_1_range_validator_dependency_x_m_l_converter.html',1,'Teuchos']]],
  ['rank',['rank',['../d6/d49/structboost_1_1numeric_1_1bindings_1_1rank.html',1,'boost::numeric::bindings']]],
  ['ranking',['Ranking',['../d3/d7f/class_ranking.html',1,'']]],
  ['rational',['RATIONAL',['../df/d85/struct_r_a_t_i_o_n_a_l.html',1,'RATIONAL'],['../db/dd0/class_rational.html',1,'Rational']]],
  ['raw_5fdecoder_5ft',['raw_decoder_t',['../d6/d7f/classzmq_1_1raw__decoder__t.html',1,'zmq']]],
  ['raw_5fencoder_5ft',['raw_encoder_t',['../d5/dbf/classzmq_1_1raw__encoder__t.html',1,'zmq']]],
  ['rawpointerconversiontraits',['RawPointerConversionTraits',['../df/d9d/class_teuchos_1_1_raw_pointer_conversion_traits.html',1,'Teuchos']]],
  ['rawpointerconversiontraits_3c_20arrayrcp_3c_20t_20_3e_20_3e',['RawPointerConversionTraits&lt; ArrayRCP&lt; T &gt; &gt;',['../db/db2/class_teuchos_1_1_raw_pointer_conversion_traits_3_01_array_r_c_p_3_01_t_01_4_01_4.html',1,'Teuchos']]],
  ['rawpointerconversiontraits_3c_20rawtype_20_2a_20_3e',['RawPointerConversionTraits&lt; RawType * &gt;',['../d1/d4e/class_teuchos_1_1_raw_pointer_conversion_traits_3_01_raw_type_01_5_01_4.html',1,'Teuchos']]],
  ['rawworkspace',['RawWorkspace',['../d2/d0c/class_teuchos_1_1_raw_workspace.html',1,'Teuchos']]],
  ['ray',['Ray',['../dd/d08/structtribits__mixed_1_1_ray.html',1,'tribits_mixed']]],
  ['ray_5ftracer',['Ray_Tracer',['../d5/dbe/classtribits__mixed_1_1_ray___tracer.html',1,'tribits_mixed']]],
  ['rcgiter',['RCGIter',['../d8/df2/class_belos_1_1_r_c_g_iter.html',1,'Belos']]],
  ['rcgiterfailure',['RCGIterFailure',['../d6/de3/class_belos_1_1_r_c_g_iter_failure.html',1,'Belos']]],
  ['rcgiterinitfailure',['RCGIterInitFailure',['../df/d63/class_belos_1_1_r_c_g_iter_init_failure.html',1,'Belos']]],
  ['rcgiterlapackfailure',['RCGIterLAPACKFailure',['../d7/d5d/class_belos_1_1_r_c_g_iter_l_a_p_a_c_k_failure.html',1,'Belos']]],
  ['rcgiterorthofailure',['RCGIterOrthoFailure',['../d3/d96/class_belos_1_1_r_c_g_iter_ortho_failure.html',1,'Belos']]],
  ['rcgiterstate',['RCGIterState',['../d6/da4/struct_belos_1_1_r_c_g_iter_state.html',1,'Belos']]],
  ['rcgsolmgr',['RCGSolMgr',['../d3/d82/class_belos_1_1_r_c_g_sol_mgr.html',1,'Belos']]],
  ['rcgsolmgr_3c_20scalartype_2c_20mv_2c_20op_2c_20true_20_3e',['RCGSolMgr&lt; ScalarType, MV, OP, true &gt;',['../d5/d81/class_belos_1_1_r_c_g_sol_mgr_3_01_scalar_type_00_01_m_v_00_01_o_p_00_01true_01_4.html',1,'Belos']]],
  ['rcgsolmgrlapackfailure',['RCGSolMgrLAPACKFailure',['../df/de2/class_belos_1_1_r_c_g_sol_mgr_l_a_p_a_c_k_failure.html',1,'Belos']]],
  ['rcgsolmgrlinearproblemfailure',['RCGSolMgrLinearProblemFailure',['../dc/d8a/class_belos_1_1_r_c_g_sol_mgr_linear_problem_failure.html',1,'Belos']]],
  ['rcgsolmgrrecyclingfailure',['RCGSolMgrRecyclingFailure',['../d2/da3/class_belos_1_1_r_c_g_sol_mgr_recycling_failure.html',1,'Belos']]],
  ['rcp',['RCP',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20_3a_3athyra_3a_3amodelevaluator_3c_20double_20_3e_20_3e',['RCP&lt; ::Thyra::ModelEvaluator&lt; double &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20_3a_3athyra_3a_3amodelevaluatorbase_3a_3ainargs_3c_20scalar_20_3e_20_3e',['RCP&lt; ::Thyra::ModelEvaluatorBase::InArgs&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20_3a_3athyra_3a_3amodelevaluatorbase_3a_3aoutargs_3c_20scalar_20_3e_20_3e',['RCP&lt; ::Thyra::ModelEvaluatorBase::OutArgs&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20a_20_3e',['RCP&lt; A &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20addertype_20_3e',['RCP&lt; AdderType &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3adgksorthomanager_20_3e',['RCP&lt; Belos::DGKSOrthoManager &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3agmrespolyop_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; Belos::GmresPolyOp&lt; ScalarType, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3alinearproblem_20_3e',['RCP&lt; Belos::LinearProblem &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3alinearproblem_3c_20double_2c_20epetra_5fmultivector_2c_20epetra_5foperator_20_3e_20_3e',['RCP&lt; Belos::LinearProblem&lt; double, Epetra_MultiVector, Epetra_Operator &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3alinearproblem_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; Belos::LinearProblem&lt; ScalarType, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3alsqrstatustest_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; Belos::LSQRStatusTest&lt; ScalarType, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3amatorthomanager_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; Belos::MatOrthoManager&lt; ScalarType, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3aorthomanager_3c_20scalartype_2c_20mv_20_3e_20_3e',['RCP&lt; Belos::OrthoManager&lt; ScalarType, MV &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3aoutputmanager_3c_20scalar_20_3e_20_3e',['RCP&lt; Belos::OutputManager&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3aoutputmanager_3c_20scalartype_20_3e_20_3e',['RCP&lt; Belos::OutputManager&lt; ScalarType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3areorthogonalizationcallback_3c_20scalar_20_3e_20_3e',['RCP&lt; Belos::ReorthogonalizationCallback&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3asolvermanager_20_3e',['RCP&lt; Belos::SolverManager &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3asolvermanager_3c_20double_2c_20epetra_5fmultivector_2c_20epetra_5foperator_20_3e_20_3e',['RCP&lt; Belos::SolverManager&lt; double, Epetra_MultiVector, Epetra_Operator &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3astatustest_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; Belos::StatusTest&lt; ScalarType, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3astatustestgenresnorm_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; Belos::StatusTestGenResNorm&lt; ScalarType, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3astatustestmaxiters_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; Belos::StatusTestMaxIters&lt; ScalarType, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3astatustestoutput_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; Belos::StatusTestOutput&lt; ScalarType, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20belos_3a_3astatustestresnorm_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; Belos::StatusTestResNorm&lt; ScalarType, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20blockgmressolmgr_3c_20double_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; BlockGmresSolMgr&lt; double, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20c_20_3e',['RCP&lt; C &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20callback_20_3e',['RCP&lt; Callback &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20_3a_3athyra_3a_3alinearopwithsolvefactorybase_3c_20scalar_20_3e_20_3e',['RCP&lt; const ::Thyra::LinearOpWithSolveFactoryBase&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20_3a_3athyra_3a_3amodelevaluator_3c_20scalar_20_3e_20_3e',['RCP&lt; const ::Thyra::ModelEvaluator&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20_3a_3athyra_3a_3avectorspacebase_3c_20scalar_20_3e_20_3e',['RCP&lt; const ::Thyra::VectorSpaceBase&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20defaultserializer_3c_20ordinal_2c_20t_20_3e_3a_3adefaultserializertype_20_3e',['RCP&lt; const DefaultSerializer&lt; Ordinal, T &gt;::DefaultSerializerType &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20enhancednumbervalidator_3c_20t_20_3e_20_3e',['RCP&lt; const EnhancedNumberValidator&lt; T &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20epetra_5fcomm_20_3e',['RCP&lt; const Epetra_Comm &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20epetra_5fcrsmatrix_20_3e',['RCP&lt; const Epetra_CrsMatrix &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20epetra_5fimport_20_3e',['RCP&lt; const Epetra_Import &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20epetra_5fmap_20_3e',['RCP&lt; const Epetra_Map &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20epetra_5fmultivector_20_3e',['RCP&lt; const Epetra_MultiVector &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20epetra_5foperator_20_3e',['RCP&lt; const Epetra_Operator &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20epetra_5fvector_20_3e',['RCP&lt; const Epetra_Vector &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20filenamevalidator_20_3e',['RCP&lt; const FileNameValidator &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20map_5ftype_20_3e',['RCP&lt; const map_type &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20mv_20_3e',['RCP&lt; const MV &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20nox_3a_3athyra_3a_3agroup_20_3e',['RCP&lt; const NOX::Thyra::Group &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20nox_3a_3athyra_3a_3avector_20_3e',['RCP&lt; const NOX::Thyra::Vector &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20objtype_20_3e',['RCP&lt; const ObjType &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20op_20_3e',['RCP&lt; const OP &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20op_5ftype_20_3e',['RCP&lt; const op_type &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20pointertype_20_3e',['RCP&lt; const PointerType &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20serializer_20_3e',['RCP&lt; const Serializer &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20stringvalidator_20_3e',['RCP&lt; const StringValidator &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20t_20_3e',['RCP&lt; const T &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3acomm_3c_20int_20_3e_20_3e',['RCP&lt; const Teuchos::Comm&lt; int &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3acondition_20_3e',['RCP&lt; const Teuchos::Condition &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3aopaquewrapper_3c_20mpi_5fcomm_20_3e_20_3e',['RCP&lt; const Teuchos::OpaqueWrapper&lt; MPI_Comm &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3aopaquewrapper_3c_20mpi_5ferrhandler_20_3e_20_3e',['RCP&lt; const Teuchos::OpaqueWrapper&lt; MPI_Errhandler &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3aparameterentry_20_3e',['RCP&lt; const Teuchos::ParameterEntry &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3aparameterentryvalidator_20_3e',['RCP&lt; const Teuchos::ParameterEntryValidator &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3aparameterlist_20_3e',['RCP&lt; const Teuchos::ParameterList &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3areferencetypereductionop_3c_20ordinal_2c_20t_20_3e_20_3e',['RCP&lt; const Teuchos::ReferenceTypeReductionOp&lt; Ordinal, T &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3aserialdensematrix_3c_20int_2c_20scalartype_20_3e_20_3e',['RCP&lt; const Teuchos::SerialDenseMatrix&lt; int, ScalarType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3aserializer_20_3e',['RCP&lt; const Teuchos::Serializer &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3aserializer_3c_20ordinal_2c_20t_20_3e_20_3e',['RCP&lt; const Teuchos::Serializer&lt; Ordinal, T &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3asimplefunctionobject_3c_20dependeetype_20_3e_20_3e',['RCP&lt; const Teuchos::SimpleFunctionObject&lt; DependeeType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3asimplefunctionobject_3c_20t_20_3e_20_3e',['RCP&lt; const Teuchos::SimpleFunctionObject&lt; T &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3astringtointegralparameterentryvalidator_3c_20int_20_3e_20_3e',['RCP&lt; const Teuchos::StringToIntegralParameterEntryValidator&lt; int &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3avaluetypereductionop_3c_20ordinal_2c_20t_20_3e_20_3e',['RCP&lt; const Teuchos::ValueTypeReductionOp&lt; Ordinal, T &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20teuchos_3a_3averboseobject_3c_20objecttype_20_3e_20_3e',['RCP&lt; const Teuchos::VerboseObject&lt; ObjectType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20thyra_3a_3alinearopwithsolvefactorybase_3c_20double_20_3e_20_3e',['RCP&lt; const Thyra::LinearOpWithSolveFactoryBase&lt; double &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20thyra_3a_3avectorbase_3c_20scalar_20_3e_20_3e',['RCP&lt; const Thyra::VectorBase&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20thyra_3a_3avectorspacebase_3c_20double_20_3e_20_3e',['RCP&lt; const Thyra::VectorSpaceBase&lt; double &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20const_20validatortype_20_3e',['RCP&lt; const ValidatorType &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20epetra_5fcomm_20_3e',['RCP&lt; Epetra_Comm &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20epetra_5fcrsgraph_20_3e',['RCP&lt; Epetra_CrsGraph &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20epetra_5fcrsmatrix_20_3e',['RCP&lt; Epetra_CrsMatrix &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20epetra_5fmap_20_3e',['RCP&lt; Epetra_Map &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20epetra_5fmultivector_20_3e',['RCP&lt; Epetra_MultiVector &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20epetra_5foperator_20_3e',['RCP&lt; Epetra_Operator &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20epetra_5frowmatrix_20_3e',['RCP&lt; Epetra_RowMatrix &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20epetra_5fvector_20_3e',['RCP&lt; Epetra_Vector &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20ifpack_5fpreconditioner_20_3e',['RCP&lt; Ifpack_Preconditioner &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20inner_5fsolver_5ftype_20_3e',['RCP&lt; inner_solver_type &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20linearproblem_3c_20double_2c_20mv_2c_20op_20_3e_20_3e',['RCP&lt; LinearProblem&lt; double, MV, OP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20loca_3a_3aglobaldata_20_3e',['RCP&lt; LOCA::GlobalData &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20loca_3a_3aparametervector_20_3e',['RCP&lt; LOCA::ParameterVector &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20loca_3a_3athyra_3a_3agroupwrapper_20_3e',['RCP&lt; LOCA::Thyra::GroupWrapper &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20loca_3a_3athyra_3a_3asavedatastrategy_20_3e',['RCP&lt; LOCA::Thyra::SaveDataStrategy &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20ml_5fepetra_3a_3amultilevelpreconditioner_20_3e',['RCP&lt; ML_Epetra::MultiLevelPreconditioner &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20mlapi_3a_3aml_5foperator_5fbox_20_3e',['RCP&lt; MLAPI::ML_Operator_Box &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20mv_20_3e',['RCP&lt; MV &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20node_5ftype_20_3e',['RCP&lt; node_type &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3aabstract_3a_3agroup_20_3e',['RCP&lt; NOX::Abstract::Group &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3aabstract_3a_3avector_20_3e',['RCP&lt; NOX::Abstract::Vector &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3adirection_3a_3ageneric_20_3e',['RCP&lt; NOX::Direction::Generic &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3aglobaldata_20_3e',['RCP&lt; NOX::GlobalData &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3alapack_3a_3agroup_20_3e',['RCP&lt; NOX::LAPACK::Group &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3alapack_3a_3amatrix_3c_20double_20_3e_20_3e',['RCP&lt; NOX::LAPACK::Matrix&lt; double &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3alapack_3a_3avector_20_3e',['RCP&lt; NOX::LAPACK::Vector &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3alinesearch_3a_3ageneric_20_3e',['RCP&lt; NOX::LineSearch::Generic &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3asolver_3a_3ageneric_20_3e',['RCP&lt; NOX::Solver::Generic &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3astatustest_3a_3acombo_20_3e',['RCP&lt; NOX::StatusTest::Combo &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3astatustest_3a_3adivergence_20_3e',['RCP&lt; NOX::StatusTest::Divergence &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3astatustest_3a_3ageneric_20_3e',['RCP&lt; NOX::StatusTest::Generic &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3astatustest_3a_3amaxiters_20_3e',['RCP&lt; NOX::StatusTest::MaxIters &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3astatustest_3a_3anormf_20_3e',['RCP&lt; NOX::StatusTest::NormF &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3astatustest_3a_3asgnchange_20_3e',['RCP&lt; NOX::StatusTest::SgnChange &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3astatustest_3a_3astagnation_20_3e',['RCP&lt; NOX::StatusTest::Stagnation &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3athyra_3a_3agroup_20_3e',['RCP&lt; NOX::Thyra::Group &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3athyra_3a_3avector_20_3e',['RCP&lt; NOX::Thyra::Vector &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20nox_3a_3autils_20_3e',['RCP&lt; NOX::Utils &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20noxlapackinterface_20_3e',['RCP&lt; NoxLapackInterface &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20op_20_3e',['RCP&lt; OP &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20serialdensematrix_3c_20int_2c_20scalartype_20_3e_20_3e',['RCP&lt; SerialDenseMatrix&lt; int, ScalarType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3abasic_5fostream_3c_20char_5ftype_2c_20traits_5ftype_20_3e_20_3e',['RCP&lt; std::basic_ostream&lt; char_type, traits_type &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3amap_3c_20std_3a_3astring_2c_20teuchos_3a_3arcp_3c_20belos_3a_3astatustest_20_3e_20_3e_20_3e',['RCP&lt; std::map&lt; std::string, Teuchos::RCP&lt; Belos::StatusTest &gt; &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3amap_3c_20std_3a_3astring_2c_20teuchos_3a_3arcp_3c_20belos_3a_3astatustest_3c_20scalartype_2c_20mv_2c_20op_20_3e_20_3e_20_3e_20_3e',['RCP&lt; std::map&lt; std::string, Teuchos::RCP&lt; Belos::StatusTest&lt; ScalarType, MV, OP &gt; &gt; &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3aostream_20_3e',['RCP&lt; std::ostream &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3aostringstream_20_3e',['RCP&lt; std::ostringstream &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20char_20_3e_20_3e',['RCP&lt; std::vector&lt; char &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20constnonconstobjectcontainer_3c_20t_20_3e_20_3e_20_3e',['RCP&lt; std::vector&lt; ConstNonconstObjectContainer&lt; T &gt; &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20double_20_3e_20_3e',['RCP&lt; std::vector&lt; double &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20fieldspec_20_3e_20_3e',['RCP&lt; std::vector&lt; FieldSpec &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20int_20_3e_20_3e',['RCP&lt; std::vector&lt; int &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20key_20_3e_20_3e',['RCP&lt; std::vector&lt; Key &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20rcp_3c_20t_20_3e_20_3e_20_3e',['RCP&lt; std::vector&lt; RCP&lt; T &gt; &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20scalar_20_3e_20_3e',['RCP&lt; std::vector&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20std_3a_3astring_20_3e_20_3e',['RCP&lt; std::vector&lt; std::string &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20t_20_2a_3e_20_3e',['RCP&lt; std::vector&lt; T *&gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20t_20_3e_20_3e',['RCP&lt; std::vector&lt; T &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20teuchos_3a_3aarray_3c_20key_20_3e_20_3e_20_3e',['RCP&lt; std::vector&lt; Teuchos::Array&lt; Key &gt; &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20teuchos_3a_3aarray_3c_20teuchos_3a_3ahashpair_3c_20key_2c_20value_20_3e_20_3e_20_3e_20_3e',['RCP&lt; std::vector&lt; Teuchos::Array&lt; Teuchos::HashPair&lt; Key, Value &gt; &gt; &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20teuchos_3a_3ahashpair_3c_20key_2c_20value_20_3e_20_3e_20_3e',['RCP&lt; std::vector&lt; Teuchos::HashPair&lt; Key, Value &gt; &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20teuchos_3a_3arcp_20_3e_20_3e',['RCP&lt; std::vector&lt; Teuchos::RCP &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20teuchos_3a_3arcp_3c_20t_20_3e_20_3e_20_3e',['RCP&lt; std::vector&lt; Teuchos::RCP&lt; T &gt; &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20teuchos_3a_3arcp_3c_20teuchos_3a_3atableentry_20_3e_20_3e_20_3e',['RCP&lt; std::vector&lt; Teuchos::RCP&lt; Teuchos::TableEntry &gt; &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20teuchos_3a_3axmlobject_20_3e_20_3e',['RCP&lt; std::vector&lt; Teuchos::XMLObject &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20std_3a_3avector_3c_20unittestdata_20_3e_20_3e',['RCP&lt; std::vector&lt; UnitTestData &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3abasic_5ffancyostream_20_3e',['RCP&lt; Teuchos::basic_FancyOStream &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3abasic_5ffancyostream_3c_20chart_2c_20traits_20_3e_20_3e',['RCP&lt; Teuchos::basic_FancyOStream&lt; CharT, Traits &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3aparameterentryvalidator_20_3e',['RCP&lt; Teuchos::ParameterEntryValidator &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3aparameterlist_20_3e',['RCP&lt; Teuchos::ParameterList &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3aserialbanddensematrix_3c_20ordinaltype_2c_20scalartype_20_3e_20_3e',['RCP&lt; Teuchos::SerialBandDenseMatrix&lt; OrdinalType, ScalarType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3aserialdensematrix_3c_20int_2c_20scalartype_20_3e_20_3e',['RCP&lt; Teuchos::SerialDenseMatrix&lt; int, ScalarType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3aserialdensematrix_3c_20ordinaltype_2c_20scalartype_20_3e_20_3e',['RCP&lt; Teuchos::SerialDenseMatrix&lt; OrdinalType, ScalarType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3aserialdensevector_3c_20int_2c_20scalartype_20_3e_20_3e',['RCP&lt; Teuchos::SerialDenseVector&lt; int, ScalarType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3aserialsymdensematrix_3c_20ordinaltype_2c_20scalartype_20_3e_20_3e',['RCP&lt; Teuchos::SerialSymDenseMatrix&lt; OrdinalType, ScalarType &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3asimplefunctionobject_3c_20t_20_3e_20_3e',['RCP&lt; Teuchos::SimpleFunctionObject&lt; T &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3atableentry_20_3e',['RCP&lt; Teuchos::TableEntry &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3atime_20_3e',['RCP&lt; Teuchos::Time &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3axmlinputstream_20_3e',['RCP&lt; Teuchos::XMLInputStream &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20teuchos_3a_3axmlobjectimplem_20_3e',['RCP&lt; Teuchos::XMLObjectImplem &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20thyra_3a_3aadaptivestatebase_20_3e',['RCP&lt; Thyra::AdaptiveStateBase &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20thyra_3a_3avectorbase_3c_20double_20_3e_20_3e',['RCP&lt; Thyra::VectorBase&lt; double &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20thyra_3a_3avectorbase_3c_20scalar_20_3e_20_3e',['RCP&lt; Thyra::VectorBase&lt; Scalar &gt; &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcp_3c_20vector_5foperator_20_3e',['RCP&lt; Vector_Operator &gt;',['../d5/d9a/class_teuchos_1_1_r_c_p.html',1,'Teuchos']]],
  ['rcpcomp',['RCPComp',['../d0/d3d/struct_teuchos_1_1_r_c_p_comp.html',1,'Teuchos']]],
  ['rcpconstcomp',['RCPConstComp',['../d7/d12/struct_teuchos_1_1_r_c_p_const_comp.html',1,'Teuchos']]],
  ['rcpdeleter',['RCPDeleter',['../d2/d63/class_teuchos_1_1_r_c_p_deleter.html',1,'Teuchos']]],
  ['rcpnode',['RCPNode',['../dc/dc9/class_teuchos_1_1_r_c_p_node.html',1,'Teuchos']]],
  ['rcpnodehandle',['RCPNodeHandle',['../dd/d46/class_teuchos_1_1_r_c_p_node_handle.html',1,'Teuchos']]],
  ['rcpnodestatistics',['RCPNodeStatistics',['../d2/d1c/struct_teuchos_1_1_r_c_p_node_tracer_1_1_r_c_p_node_statistics.html',1,'Teuchos::RCPNodeTracer']]],
  ['rcpnodethrowdeleter',['RCPNodeThrowDeleter',['../d9/d81/class_teuchos_1_1_r_c_p_node_throw_deleter.html',1,'Teuchos']]],
  ['rcpnodetmpl',['RCPNodeTmpl',['../d6/dc9/class_teuchos_1_1_r_c_p_node_tmpl.html',1,'Teuchos']]],
  ['rcpnodetracer',['RCPNodeTracer',['../d2/dba/class_teuchos_1_1_r_c_p_node_tracer.html',1,'Teuchos']]],
  ['re_5fbackref_5fcache_5fentry',['re_backref_cache_entry',['../d5/d4d/structre__backref__cache__entry.html',1,'']]],
  ['re_5fcharset_5ft',['re_charset_t',['../de/dc4/structre__charset__t.html',1,'']]],
  ['re_5fdfa_5ft',['re_dfa_t',['../d5/d6f/structre__dfa__t.html',1,'']]],
  ['re_5fdfastate_5ft',['re_dfastate_t',['../d5/dbb/structre__dfastate__t.html',1,'']]],
  ['re_5ffail_5fstack_5fent_5ft',['re_fail_stack_ent_t',['../dd/d6f/structre__fail__stack__ent__t.html',1,'']]],
  ['re_5ffail_5fstack_5ft',['re_fail_stack_t',['../de/d42/structre__fail__stack__t.html',1,'']]],
  ['re_5fmatch_5fcontext_5ft',['re_match_context_t',['../d5/db1/structre__match__context__t.html',1,'']]],
  ['re_5fnode_5fset',['re_node_set',['../d1/dde/structre__node__set.html',1,'']]],
  ['re_5fpattern_5fbuffer',['re_pattern_buffer',['../db/d0e/structre__pattern__buffer.html',1,'']]],
  ['re_5fregisters',['re_registers',['../d6/d14/structre__registers.html',1,'']]],
  ['re_5fsift_5fcontext_5ft',['re_sift_context_t',['../d7/d02/structre__sift__context__t.html',1,'']]],
  ['re_5fstate_5ftable_5fentry',['re_state_table_entry',['../d6/dd8/structre__state__table__entry.html',1,'']]],
  ['re_5fstring_5ft',['re_string_t',['../da/d76/structre__string__t.html',1,'']]],
  ['re_5fsub_5fmatch_5flast_5ft',['re_sub_match_last_t',['../df/db4/structre__sub__match__last__t.html',1,'']]],
  ['re_5fsub_5fmatch_5ftop_5ft',['re_sub_match_top_t',['../d6/dbd/structre__sub__match__top__t.html',1,'']]],
  ['re_5ftoken_5ft',['re_token_t',['../d0/d92/structre__token__t.html',1,'']]],
  ['reader',['Reader',['../d5/d0d/class_teuchos_1_1_matrix_market_1_1_raw_1_1_reader.html',1,'Teuchos::MatrixMarket::Raw']]],
  ['reader_5fcontext',['reader_context',['../d4/d23/structreader__context.html',1,'']]],
  ['real_5fattribute',['REAL_ATTRIBUTE',['../d1/d98/struct_r_e_a_l___a_t_t_r_i_b_u_t_e.html',1,'']]],
  ['real_5fpart_5fview',['real_part_view',['../d7/d4f/structboost_1_1numeric_1_1bindings_1_1result__of_1_1real__part__view.html',1,'boost::numeric::bindings::result_of']]],
  ['real_5ftime_5fsync_5ft',['real_time_sync_t',['../d5/d1c/structreal__time__sync__t.html',1,'']]],
  ['realsolvermanager',['RealSolverManager',['../d3/d0b/class_belos_1_1_details_1_1_real_solver_manager.html',1,'Belos::Details']]],
  ['realsolvermanager_3c_20scalartype_2c_20mv_2c_20op_2c_20false_20_3e',['RealSolverManager&lt; ScalarType, MV, OP, false &gt;',['../d3/d74/class_belos_1_1_details_1_1_real_solver_manager_3_01_scalar_type_00_01_m_v_00_01_o_p_00_01false_01_4.html',1,'Belos::Details']]],
  ['realsolvermanager_3c_20scalartype_2c_20mv_2c_20op_2c_20teuchos_3a_3ascalartraits_3c_20scalartype_20_3e_3a_3aiscomplex_20_3e',['RealSolverManager&lt; ScalarType, MV, OP, Teuchos::ScalarTraits&lt; ScalarType &gt;::isComplex &gt;',['../d3/d0b/class_belos_1_1_details_1_1_real_solver_manager.html',1,'Belos::Details']]],
  ['realsolvermanager_3c_20scalartype_2c_20mv_2c_20op_2c_20true_20_3e',['RealSolverManager&lt; ScalarType, MV, OP, true &gt;',['../d5/d6b/class_belos_1_1_details_1_1_real_solver_manager_3_01_scalar_type_00_01_m_v_00_01_o_p_00_01true_01_4.html',1,'Belos::Details']]],
  ['reaper_5ft',['reaper_t',['../db/d85/classzmq_1_1reaper__t.html',1,'zmq']]],
  ['rebind',['rebind',['../d3/d0b/structgc__allocator__ignore__off__page_1_1rebind.html',1,'gc_allocator_ignore_off_page&lt; GC_Tp &gt;::rebind&lt; GC_Tp1 &gt;'],['../df/d0b/structtraceable__allocator_1_1rebind.html',1,'traceable_allocator&lt; GC_Tp &gt;::rebind&lt; GC_Tp1 &gt;'],['../dc/da6/structgc__allocator_1_1rebind.html',1,'gc_allocator&lt; GC_Tp &gt;::rebind&lt; GC_Tp1 &gt;'],['../d2/d80/struct_teuchos_1_1_details_1_1_allocator_1_1rebind.html',1,'Teuchos::Details::Allocator&lt; T &gt;::rebind&lt; U &gt;']]],
  ['record_5fdescription',['record_description',['../dd/d4d/structrecord__description.html',1,'']]],
  ['reducedaesettings',['ReduceDAESettings',['../d4/dbf/class_reduce_d_a_e_settings.html',1,'']]],
  ['reducedhessiancalculator',['ReducedHessianCalculator',['../de/d9a/class_ipopt_1_1_reduced_hessian_calculator.html',1,'Ipopt']]],
  ['reduction',['Reduction',['../da/d45/class_reduction.html',1,'']]],
  ['refarray',['RefArray',['../d8/d5a/class_ref_array.html',1,'']]],
  ['refarray2carray',['RefArray2CArray',['../d8/d49/struct_ref_array2_c_array.html',1,'']]],
  ['refarray_3c_20t_2c_20size_20_3e',['RefArray&lt; T, size &gt;',['../d8/d5a/class_ref_array.html',1,'']]],
  ['refarray_3c_20t_2c_20size1_20_2asize2_20_2asize3_20_3e',['RefArray&lt; T, size1 *size2 *size3 &gt;',['../d8/d5a/class_ref_array.html',1,'']]],
  ['refarray_3c_20t_2c_20size1_20_2asize2_20_3e',['RefArray&lt; T, size1 *size2 &gt;',['../d8/d5a/class_ref_array.html',1,'']]],
  ['refarraydim1',['RefArrayDim1',['../d1/d6f/class_ref_array_dim1.html',1,'']]],
  ['refarraydim2',['RefArrayDim2',['../d7/d5a/class_ref_array_dim2.html',1,'']]],
  ['refarraydim3',['RefArrayDim3',['../db/d8a/class_ref_array_dim3.html',1,'']]],
  ['referencedobject',['ReferencedObject',['../da/d10/class_ipopt_1_1_referenced_object.html',1,'Ipopt']]],
  ['referencer',['Referencer',['../de/dc9/class_ipopt_1_1_referencer.html',1,'Ipopt']]],
  ['referencetypedeserializationbuffer',['ReferenceTypeDeserializationBuffer',['../d4/d75/class_teuchos_1_1_reference_type_deserialization_buffer.html',1,'Teuchos']]],
  ['referencetypereductionop',['ReferenceTypeReductionOp',['../da/dc1/class_teuchos_1_1_reference_type_reduction_op.html',1,'Teuchos']]],
  ['referencetypeserializationbuffer',['ReferenceTypeSerializationBuffer',['../d2/d98/class_teuchos_1_1_reference_type_serialization_buffer.html',1,'Teuchos']]],
  ['refill_5fdata',['refill_data',['../d5/d57/structrefill__data.html',1,'']]],
  ['refmaxwellpreconditioner',['RefMaxwellPreconditioner',['../d1/dd2/class_ref_maxwell_preconditioner.html',1,'RefMaxwellPreconditioner'],['../d0/da9/class_m_l___epetra_1_1_ref_maxwell_preconditioner.html',1,'ML_Epetra::RefMaxwellPreconditioner']]],
  ['refnum',['refnum',['../d1/d2a/structrefnum.html',1,'']]],
  ['register_5finfo_5ftype',['register_info_type',['../d7/d49/unionregister__info__type.html',1,'']]],
  ['registeredoption',['RegisteredOption',['../de/d28/class_ipopt_1_1_registered_option.html',1,'Ipopt']]],
  ['registeredoptions',['RegisteredOptions',['../db/d6a/class_ipopt_1_1_registered_options.html',1,'Ipopt']]],
  ['registeredtnlp',['RegisteredTNLP',['../d7/d2c/class_registered_t_n_l_p.html',1,'']]],
  ['registeredtnlps',['RegisteredTNLPs',['../db/dc1/class_registered_t_n_l_ps.html',1,'']]],
  ['registerfactorya',['RegisterFactoryA',['../d1/d81/class_a_1_1_register_factory_a.html',1,'A']]],
  ['registerfactoryb',['RegisterFactoryB',['../d6/d2f/class_b_1_1_register_factory_b.html',1,'B']]],
  ['registerfactoryc',['RegisterFactoryC',['../d3/d7e/class_c_1_1_register_factory_c.html',1,'C']]],
  ['regmatch_5ft',['regmatch_t',['../d3/d3a/structregmatch__t.html',1,'']]],
  ['relerrsmallnumber',['RelErrSmallNumber',['../d9/d78/class_teuchos_1_1_rel_err_small_number.html',1,'Teuchos']]],
  ['relerrsmallnumber_3c_20false_2c_20scalar_20_3e',['RelErrSmallNumber&lt; false, Scalar &gt;',['../d8/dd2/class_teuchos_1_1_rel_err_small_number_3_01false_00_01_scalar_01_4.html',1,'Teuchos']]],
  ['relerrsmallnumber_3c_20true_2c_20scalar_20_3e',['RelErrSmallNumber&lt; true, Scalar &gt;',['../d8/d17/class_teuchos_1_1_rel_err_small_number_3_01true_00_01_scalar_01_4.html',1,'Teuchos']]],
  ['remoterepoandbranch',['RemoteRepoAndBranch',['../de/ddb/class_checkin_test_1_1_remote_repo_and_branch.html',1,'CheckinTest']]],
  ['remove_5fimaginary',['remove_imaginary',['../d1/d58/structboost_1_1numeric_1_1bindings_1_1remove__imaginary.html',1,'boost::numeric::bindings']]],
  ['remove_5fimaginary_3c_20const_20std_3a_3acomplex_3c_20t_20_3e_20_3e',['remove_imaginary&lt; const std::complex&lt; T &gt; &gt;',['../da/da0/structboost_1_1numeric_1_1bindings_1_1remove__imaginary_3_01const_01std_1_1complex_3_01_t_01_4_01_4.html',1,'boost::numeric::bindings']]],
  ['remove_5fimaginary_3c_20std_3a_3acomplex_3c_20t_20_3e_20_3e',['remove_imaginary&lt; std::complex&lt; T &gt; &gt;',['../d8/d61/structboost_1_1numeric_1_1bindings_1_1remove__imaginary_3_01std_1_1complex_3_01_t_01_4_01_4.html',1,'boost::numeric::bindings']]],
  ['reorthogonalizationcallback',['ReorthogonalizationCallback',['../d3/dfb/class_belos_1_1_reorthogonalization_callback.html',1,'Belos']]],
  ['rep_5ft',['rep_t',['../d7/d23/classzmq_1_1rep__t.html',1,'zmq']]],
  ['repeatedjob',['RepeatedJob',['../d4/dfb/struct_repeated_job.html',1,'']]],
  ['repoextraremotepulls',['RepoExtraRemotePulls',['../d3/df8/class_checkin_test_1_1_repo_extra_remote_pulls.html',1,'CheckinTest']]],
  ['repostatsstruct',['RepoStatsStruct',['../d3/dc3/classgitdist_1_1_repo_stats_struct.html',1,'gitdist']]],
  ['repostattable',['RepoStatTable',['../de/d27/classgitdist_1_1_repo_stat_table.html',1,'gitdist']]],
  ['req_5fsession_5ft',['req_session_t',['../d3/d3d/classzmq_1_1req__session__t.html',1,'zmq']]],
  ['req_5ft',['req_t',['../d7/d9d/classzmq_1_1req__t.html',1,'zmq']]],
  ['request_5fio',['request_io',['../dc/d89/structrequest__io.html',1,'']]],
  ['residual',['Residual',['../d2/d15/class_m_l_a_p_i_1_1_residual.html',1,'MLAPI']]],
  ['responsedescription',['ResponseDescription',['../d0/d1d/struct_response_description.html',1,'']]],
  ['restoconvergencecheck',['RestoConvergenceCheck',['../d7/d37/class_ipopt_1_1_resto_convergence_check.html',1,'Ipopt']]],
  ['restofilterconvergencecheck',['RestoFilterConvergenceCheck',['../d3/df1/class_ipopt_1_1_resto_filter_convergence_check.html',1,'Ipopt']]],
  ['restoipoptnlp',['RestoIpoptNLP',['../d1/da5/class_ipopt_1_1_resto_ipopt_n_l_p.html',1,'Ipopt']]],
  ['restoiterateinitializer',['RestoIterateInitializer',['../dc/d97/class_ipopt_1_1_resto_iterate_initializer.html',1,'Ipopt']]],
  ['restoiterationoutput',['RestoIterationOutput',['../d1/d05/class_ipopt_1_1_resto_iteration_output.html',1,'Ipopt']]],
  ['restopenaltyconvergencecheck',['RestoPenaltyConvergenceCheck',['../d1/df4/class_ipopt_1_1_resto_penalty_convergence_check.html',1,'Ipopt']]],
  ['restorationphase',['RestorationPhase',['../d4/dbd/class_ipopt_1_1_restoration_phase.html',1,'Ipopt']]],
  ['restorestorationphase',['RestoRestorationPhase',['../d5/d46/class_ipopt_1_1_resto_restoration_phase.html',1,'Ipopt']]],
  ['result_5fof_5fget',['result_of_get',['../d1/d02/structboost_1_1numeric_1_1bindings_1_1detail_1_1result__of__get.html',1,'boost::numeric::bindings::detail']]],
  ['ringbuffer',['RINGBUFFER',['../d1/ded/struct_r_i_n_g_b_u_f_f_e_r.html',1,'']]],
  ['rk12',['RK12',['../dc/dfc/class_r_k12.html',1,'']]],
  ['rk12settings',['RK12Settings',['../d4/dcc/class_r_k12_settings.html',1,'']]],
  ['rk4_5fdata',['RK4_DATA',['../dc/d80/struct_r_k4___d_a_t_a.html',1,'']]],
  ['roots',['roots',['../dc/d58/structroots.html',1,'']]],
  ['rosenbrockmodelevaluator',['RosenbrockModelEvaluator',['../da/d7a/class_rosenbrock_model_evaluator.html',1,'']]],
  ['rot_5fimpl',['rot_impl',['../da/d7b/structboost_1_1numeric_1_1bindings_1_1blas_1_1rot__impl.html',1,'boost::numeric::bindings::blas']]],
  ['rotg_5fimpl',['rotg_impl',['../dc/d0a/structboost_1_1numeric_1_1bindings_1_1blas_1_1rotg__impl.html',1,'boost::numeric::bindings::blas']]],
  ['rotm_5fimpl',['rotm_impl',['../d3/db4/structboost_1_1numeric_1_1bindings_1_1blas_1_1rotm__impl.html',1,'boost::numeric::bindings::blas']]],
  ['rotmg_5fimpl',['rotmg_impl',['../d0/df0/structboost_1_1numeric_1_1bindings_1_1blas_1_1rotmg__impl.html',1,'boost::numeric::bindings::blas']]],
  ['router_5ft',['router_t',['../d0/d00/classzmq_1_1router__t.html',1,'zmq']]],
  ['row',['row',['../da/d1f/structboost_1_1numeric_1_1bindings_1_1result__of_1_1row.html',1,'boost::numeric::bindings::result_of']]],
  ['row_5fwrapper',['row_wrapper',['../d2/db1/structboost_1_1numeric_1_1bindings_1_1detail_1_1row__wrapper.html',1,'boost::numeric::bindings::detail']]],
  ['rowmatrix',['RowMatrix',['../dd/d7f/class_m_l___epetra_1_1_row_matrix.html',1,'ML_Epetra']]],
  ['rside',['rside',['../dc/d5a/structrside.html',1,'']]],
  ['rtclock_5ft',['rtclock_t',['../da/d1a/unionrtclock__t.html',1,'']]],
  ['rteuler',['RTEuler',['../dc/dce/class_r_t_euler.html',1,'']]],
  ['rteulersettings',['RTEulerSettings',['../d8/dc5/class_r_t_euler_settings.html',1,'']]],
  ['rusage',['rusage',['../d6/ddd/structrusage.html',1,'']]],
  ['rws',['rws',['../da/d46/structrws.html',1,'']]],
  ['rws1',['rws1',['../da/d44/structrws1.html',1,'']]]
];
